// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  google_rating: defineAsyncComponent(() => import("./GoogleRating/index.vue")),
  grid_three_columns: defineAsyncComponent(
    () => import("./GridThreeColumns/index.vue")
  ),
  grid_two_columns: defineAsyncComponent(
    () => import("./GridTwoColumns/index.vue")
  ),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  instructor_listing: defineAsyncComponent(
    () => import("./InstructorListing/index.vue")
  ),
  job_posting: defineAsyncComponent(() => import("./JobPosting/index.vue")),
  question_answer: defineAsyncComponent(
    () => import("./QuestionAnswer/index.vue")
  ),
  service_pricing: defineAsyncComponent(
    () => import("./ServicePricing/index.vue")
  ),
  simple_text_block: defineAsyncComponent(
    () => import("./SimpleTextBlock/index.vue")
  ),
  uniuqe_selling_points: defineAsyncComponent(
    () => import("./UniuqeSellingPoints/index.vue")
  ),
  useful_links: defineAsyncComponent(() => import("./UsefulLinks/index.vue")),
});
